### PR TITLE
:construction_worker: feat: migrate to bun

### PR DESCRIPTION
**Pull request by roninjin10**
## Description

Migrate from pnpm and node to bun

## Testing

Explain the quality checks that have been done on the code changes

## Additional Information

- [ ] I read the [contributing docs](../docs/contributing.md) (if this is your first contribution)

Your ENS/address:

### CODE REVIEW

**Comment by roninjin10** [comment]
Current dependencies on/for this PR:
* main
  * **PR #474** <a href="https://app.graphite.dev/github/pr/evmts/evmts-monorepo/474" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/evmts/evmts-monorepo/474?utm_source=stack-comment).

**Review by o-az — CHANGES_REQUESTED** [review]
@roninjin10 are you expecting ci jobs to fail? As far as bun I don't see any issues, unless builds are failing because of the migration in which case I will investigate. Need to know first if you're expecting jobs to fail

**Comment by roninjin10** [comment]
@o-az no ci jobs should not be failing this pr is broken still

**Comment by roninjin10** [comment]
Bun is highly buggy in monorepos using pnpm for package manager and bun for running scripts. Nx will keep using pnpm as well

**Comment by o-az** [comment]
wise move

**Pull request closed without merging**
